[project]
name = "superquantization"
version = "0.1.0"
description = "Super Quantization is a package that provides an emulation of an int2 quantization."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "accelerate>=0.26.0",
    "black>=24.10.0",
    "datasets>=3.2.0",
    "density",
    "frease",
    "ipykernel>=6.29.5",
    "matplotlib>=3.10.0",
    "ruff>=0.8.3",
    "skypilot>=0.7.0",
    "torch>=2.5.1",
    "torchvision>=0.20.1",
    "tqdm>=4.67.1",
    "transformers>=4.47.1",
]

[tool.uv.sources]
density = { path = "../Density/dist/density-0.1.0.tar.gz" }
frease = { path = "../FrEase/dist/frease-0.1.0-py3-none-any.whl" }
